workflows:
  android_debug:
    name: Android Debug
    max_build_duration: 45
    instance_type: linux_x2
    environment:
      java: 17
    scripts:
      - chmod +x gradlew || true
      - ./gradlew clean assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
